### ISSUE TITLE
FYI: Time handling bug affects Current Event and Next Event time display

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#9]
Looks like the time bug in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/467 and https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/302 can affect the event display in status block. Opening this as a reminder to confirm fix after those upstream bugs are fixed on here too.

![Screenshot_20221111-114921](https://user-images.githubusercontent.com/9244278/201411018-f83de5de-fb62-4989-8954-8937566893eb.jpg)

![Screenshot_20221111-115008](https://user-images.githubusercontent.com/9244278/201411021-94479300-a345-4bf6-8cd2-f894268e5aa7.jpg)

**Comment by KipK** [comment]
I've fixed this also time should be uniform now, thanks

**Comment by fhteagle** [comment]
With commit 37ee7437c49b877ed87b15f5052aaf2a469046eb : 

Time display of Event and Schedule lines are showing erroneous times. Correct values are supposed to be disabled at 14:30 aka 2:30PM local and enabled at 23:00 aka 11PM local for the below screenshot (I checked /schedule endpoint and the text values are correct).

![Screenshot_20221111_173223](https://user-images.githubusercontent.com/9244278/201447762-6e02ed7c-a90f-4eec-b214-370c2530dca8.png)

**Comment by KipK** [comment]
I think I have fixed it now.

**Comment by fhteagle** [comment]
At commit: 6854250b3fa094650959c3cd12bb6d0c17dd2bdd

Event lines are correct, but schedule table still has erroneous time:

![Screenshot_20221112_080312](https://user-images.githubusercontent.com/9244278/201480343-45c03412-5d63-4f2e-8efb-f8cb8d71e9e3.png)

Also, I like the calendar icons instead of the word event, looks cleaner!

**Comment by KipK** [comment]
this is an outdated version, I think it was fixed while you've tested this one ;)
tags now has same size

**Comment by fhteagle** [comment]
Lol yeah why I am careful to reference the commit that git pull got me up to. 

Tested again at commit ending in 144e58 , but still seeing wrong time values in the schedule edit table. Same erroneous values for schedule id lines "2" and "3" as my previous screen shot.

This is output of /schedule endpoint:

```
[{"id":2,"state":"active","time":"23:00:00","days":["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]},{"id":3,"state":"disabled","time":"14:30:00","days":["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]}]
```

**Comment by KipK** [comment]
Mmhh that looks strange, as it use exactly the same function for displaying time from timers & plan.

Here it works : 
![image](https://user-images.githubusercontent.com/488789/201532863-ecd91c43-7ca5-4a65-b7fe-205f3cef9086.png)

**Comment by fhteagle** [comment]
A couple more data points:

I deleted my schedule table (and noticed the Auto button goes away with an empty schedule, which is a nice touch!). Re-added my schedule lines and checked on /schedule endpoint, and all seemed correct there. 

But I changed my time zone to NTP based Europe/Paris just to test. The /schedule endpoint raw values stayed the same, the event lines in the status block changed to the wrong values (same as schedule edit lines), and the schedule edit lines stayed the wrong time.

BTW, time input for schedule line items is back to being 24 hour based input, I thought it was allowed to follow the browser config?

**Comment by KipK** [comment]
the native time/date input fields in Browsers comes from OS regional settings. There's no way to change that from javascript or to force a different display.
The "toLocaleString" javascript function to convert date/time to local format use the browser regional settings.

That perhaps explain why you have a different display while testing

**Comment by fhteagle** [comment]
Checked it again in Firefox and Chrome, both have 12 hr based input boxes for schedule editing. Vivaldi seems to be very much thrown for a loop at my attempt to have ISO 8601 time format as the default on my machine. Oops.

However, all three browsers definitely had the wrong times displayed on the schedule table.

**Comment by KipK** [comment]
I have changed for the Nuxon time lib yeserday, this cleans up lot oif time manipulation.
Is it still wrong ?

**Comment by fhteagle** [comment]
at commit: 0dece329ce867a10133fe91298f0cf85cd7677b2

- Editing schedule table gives correct values in /schedule endpoint
- Status block event lines are correct (I like the word "timer", good change there)
- Schedule table lines are correct
- On Configuration > System page, Textbox is dd/mm/yyyy --:-- when NTP is selected, initially when Manual time is selected, and after a manual set time operation
- Manual set time operation works (checked against /status endpoint)
- Use Browser Time button does NOT work

Two steps forward, minor step back

**Comment by KipK** [comment]
Ho yeah I've put localised time format in the input field. Fiexed now

**Comment by KipK** [comment]
> * Status block event lines are correct (I like the word "timer", good change there)

What I'll do here, is displaying the current claim . I know use the "/claims/target" endpoint

So if there is a state active/disable coming from OCPP, Divert, whatever, it will be displayed here in place of current timer ( need to find icons for Divert, Ocpp, Ohm & Mqtt )
Next timer will always display if there's one.

This way we always now what is controlling the system, without bloating the interface with a new dedicated area

**Comment by fhteagle** [comment]
At 9f04ea5632dde4030e44a17d82beaa51b2c5bffe 

"Use Browser Time" button still makes the time input text box go to dd/mm/yyyy --:-- .

**Comment by KipK** [comment]
yeah I have fixed that, but it's now on a branch I can't publish yet.
I'm rewriting the data management logic and from now everything is broken.

**Comment by KipK** [comment]
Lof of fixes & improvment in latest commit. 
However, you'll need a special OpenEvse WiFi build of my "testing" branch as my changes are not in main yet:

https://github.com/KipK/ESP32_WiFi_V4.x/tree/testing

If you want a fresh build for openevse_wifi_v1 : 
[firmware.zip](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/files/10013038/firmware.zip)

Now a tags with a Robot icon & the associated service name ( Divert, Ocpp, ... )  will display like for the Manual one if a service has priority on the "state" claim. 
Now/Next timers status are hidden ( like for Manual mode ) 

![image](https://user-images.githubusercontent.com/488789/201902535-bcbf3838-88da-4b16-baca-4c3849444654.png)

**Comment by fhteagle** [comment]
I want to leave my OpenEVSE on 4.1.5 for at least this week, as I will be driving and charging quite a bit. I can test your firmware build after the 19 Nov probably.

"Use Browser Time" button appears to be fixed in commit 68654ca8891a2b27be8970e77063540bb25bb9c6

I think that is all the time based bugs in your GUI, other than problems introduced by #467. But I think we should leave this issue open until #467 is confirmed solved.
